jinaga/jinaga.js

- package-lock.json
- src/authentication/authentication-device.ts
- src/authentication/authentication-impl.ts
- src/authentication/authentication-noop.ts
- src/authentication/authentication-offline.ts
- src/authentication/authentication-session.ts
- src/authentication/authentication-test.ts
- src/authentication/authentication.ts
- src/feed/feed-impl.ts
- src/feed/feed.ts
- src/fork/channel-processor.ts
- src/fork/channel.ts
- src/fork/fork.ts
- src/fork/pass-through-fork.ts
- src/fork/persistent-fork.ts
- src/fork/transient-fork.ts
- src/jinaga-server.ts
- src/jinaga.ts
- src/subscription/subscription-impl.ts
- src/subscription/subscription-no-op.ts
- src/subscription/subscription.ts
- src/watch/watch-impl.ts
- test/fact/knownHashSpec.ts
- test/watch/mock-authentication.ts
- Implement subscription with simple pooling
- Fix this reference of channel
- Fixed mock authentication implementation
- Upgraded NPM
- Test known hashes
- Compute the hash of a fact with an integer field
- Sequence the notifications of facts added so that they happen in topological order
- Updated dependencies
> Subscribe for live updates

- package-lock.json
- src/jinaga.ts
- src/query/query-parser.ts
More accurate type declaration, which permits generic function call instead of type assertion.
> Partial template

- src/index.ts
- src/jinaga.ts
- src/query/query-parser.ts
- src/template.ts
- test/authorization/authorizationExampleSpec.ts
- test/authorization/authorizationRulesSpec.ts
- test/watch/nestedWatchSpec.ts
- test/watch/watchSpec.ts
Use recursive type to allow partial predecessors.
> Define a template type.

- package-lock.json
- package.json
The old driver hangs on Node 16
> Upgrade Postgres driver

- src/index.ts
Allow consumers to use the topological sorter class
> Expose the topological sorter

- src/observer/observer.ts
- src/specification/inverse.ts
- test/specification/inverseSpec.ts
The inverse will already contain the necessary conditions to determine
if the add or remove would indeed be effective.
> Removed the maybeAdd and maybeRemove operations.

- src/observer/observer.ts
- test/specification/watchSpec.ts
- Add existing child projections
- Recursively notify existing grandchildren
> Notify existing child projections

- src/observer/observer.ts
- src/util/trace.ts
- Added info trace
- Added metric trace
- Trace observed tuples added and removed
> Trace information and metrics

- src/managers/NetworkManager.ts
- src/managers/factManager.ts
- src/observable/observable.ts
- Fork feeds to avoid duplication
- Batch load operations
- Fixed early resolve
- Simplify promise
- Notify of facts added during load
> Optimize feeds

- src/index.ts
- src/jinaga.ts
- src/specification/model.ts
- Export types for observables
- ProjectionOf utility type
> Export observable

- src/authorization/authorization-noop.ts
- src/authorization/authorization.ts
- src/distribution/distribution-engine.ts
- src/distribution/distribution-rules.ts
- src/indexeddb/indexeddb-store.ts
- src/jinaga-test.ts
- src/managers/NetworkManager.ts
- src/memory/memory-store.ts
- src/specification/feed-builder.ts
- src/specification/feed.ts
- src/storage.ts
- test/blogModel.ts
- test/companyModel.ts
- test/distribution/distributionRuleSpec.ts
- test/specification/feedBuilderSpec.ts
- test/specification/givenSpec.ts
- test/specification/inverseSpec.ts
- test/specification/querySpec.ts
- test/specification/splitSpecificationSpec.ts
- test/specification/watchSpec.ts
Define rules by which facts can be distributed to certain users.
> Distribution rules

- src/authorization/authorization-noop.ts
- src/authorization/authorization.ts
- src/distribution/distribution-engine.ts
- src/managers/NetworkManager.ts
- Add the verifyDistributor method to Authorization
- Check multiple feeds in distribution engine
> Refine distribution rules

- src/distribution/distribution-engine.ts
- src/managers/NetworkManager.ts
- src/specification/feed.ts
- src/specification/specification.ts
- test/distribution/distributionRuleSpec.ts
- Allow identity specifications in distribution rules
- Describe failures to distribute
> Identity distribution

- src/distribution/distribution-rules.ts
- src/index.ts
- src/specification/specification-parser.ts
- test/distribution/distributionDescriptionSpec.ts
- Describe distribution rules
- Load distribution rules from description
> Load distribution rules from description

- src/authorization/authorizationRules.ts
- src/http/httpNetwork.ts
- src/http/web-client.ts
- src/http/xhr.ts
- src/jinaga.ts
- src/managers/NetworkManager.ts
- src/managers/factManager.ts
- src/model/user.ts
- src/observer/observer.ts
- src/observer/subscriber.ts
- Subscribe to keep connection open
- Fixed User and Device types
- Open the socket before setting headers
> Subscribe for real-time notification

- src/specification/model.ts
- test/specification/watchSpec.ts
> Test watch with identity specification.

- eslint.config.mjs
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/jinaga/jinaga.js/pull/98?shareId=892bd4b7-69e8-47ce-aa84-a7b562681a91).
> Fix the build error due to incorrect eslint configuration

- src/authorization/authorizationRules.ts
- src/distribution/distribution-rules.ts
- src/index.ts
- src/rules/RuleSet.ts
- src/specification/specification-parser.ts
- test/rules/RuleSetSpec.ts
- **Restructure parser so that we can parse a rule set**
- **Test the ability to load a rule set from text**
> Parse a rule set

- src/observable/observable.ts
Fixes [https://github.com/jinaga/jinaga.js/security/code-scanning/2](https://github.com/jinaga/jinaga.js/security/code-scanning/2)
To fix the prototype pollution vulnerability, we should ensure that the keys used to index into objects cannot be `__proto__`, `constructor`, or `prototype`. This can be achieved by adding a check to reject these keys before using them. Alternatively, we can use a `Map` object instead of a plain object for `listenersByTypeAndSpecification` and `listenersBySpecification`, as `Map` is not vulnerable to prototype pollution.
The best way to fix the problem without changing existing functionality is to use a `Map` object for `listenersByTypeAndSpecification` and `listenersBySpecification`. This approach ensures that the keys are safely handled without the risk of …
> Fix code scanning alert no. 2: Prototype-polluting assignment

- .roomodes
- src/jinaga.ts
- test/fact/factSpec.ts
Introduce validation and handling for nullable predecessors in facts, ensuring they are omitted from the canonical form and do not cause errors during creation. Add tests to verify the behavior for both null and undefined predecessors.
> Handle nullable predecessors in facts

- documentation/connection-lifecycle-analysis.md
- src/jinaga-browser.ts
- src/jinaga-test.ts
- src/managers/NetworkManager.ts
- src/managers/factManager.ts
- src/observer/subscriber.ts
Introduce comprehensive documentation for connection lifecycle management and add a configurable refresh interval for network connections.
> Add refresh interval configuration

- src/observable/observable.ts
Introduce diagnostic logging to enhance observability of the observable source.
> Add diagnostic logging to observable source
